[package]
name = "kornia-apriltag-detector"
version = "1.0.0"
edition = "2021"

[dependencies]
kornia-apriltag = "0.1.10"
kornia-image = "0.1"
kornia-imgproc = "0.1"
kornia-io = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
